# Copy this file into the following folder:
#    Linux: /etc/newrelic-infra/integrations.d
#    Windows: C:\Program Files\New Relic\newrelic-infra\integrations.d
#
# For a complete description of the Configuration File Specification, please
# refer to the Integrations SDK documentation:
# https://docs.newrelic.com/docs/integrations/integrations-sdk/file-specifications

integration_name: com.newrelic.nri-mssql

instances:
  - name: nri-mssql
    command: all_data
